const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const cases={vesper:{index:"01 / FINTECH",title:"Vesper Finance",accent:"#805cff",intro:"A speculative wealth platform that turns complex portfolio intelligence into a calm, high-contrast daily ritual.",role:"Product direction + creative development",year:"2026",scope:"Strategy / UX / Motion / Frontend"},nami:{index:"02 / MOBILITY",title:"Nami Mobility",accent:"#ff774d",intro:"A city-scale mobility identity built around warm geometry, live route behavior and interfaces that feel more human than infrastructural.",role:"Brand system + interface",year:"2026",scope:"Identity / Product / Motion"},morrow:{index:"03 / MACHINE INTELLIGENCE",title:"Morrow AI",accent:"#49d8ff",intro:"An identity and prototype for an intelligence layer that explains not only what it predicts, but the uncertainty behind every answer.",role:"Art direction + prototype",year:"2026",scope:"Identity / Research / Interaction"},afterdark:{index:"04 / CULTURE",title:"Afterdark Archive",accent:"#d9ff43",intro:"A living index for electronic culture: part archive, part publication, part event signal. Designed to feel discovered rather than browsed.",role:"Creative direction + platform",year:"2025",scope:"Editorial / Identity / Web"}};
const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
const revealObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add("in");revealObserver.unobserve(entry.target)}},{threshold:.12,rootMargin:"0px 0px -40px"});$$(".reveal").forEach((el,i)=>{el.style.transitionDelay=Math.min(i%5,4)*45+"ms";revealObserver.observe(el)});
const nav=$(".nav"),bar=$(".progress span");function onScroll(){nav.classList.toggle("scrolled",scrollY>20);const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max?scrollY/max*100:0)+"%"}addEventListener("scroll",onScroll,{passive:true});onScroll();
const dot=$(".cursor-dot"),ring=$(".cursor-ring");if(matchMedia("(pointer:fine)").matches){let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;addEventListener("pointermove",e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+"px";dot.style.top=my+"px"});const loop=()=>{rx+=(mx-rx)*.16;ry+=(my-ry)*.16;ring.style.left=rx+"px";ring.style.top=ry+"px";requestAnimationFrame(loop)};loop();$$("a,button,.project").forEach(el=>{el.addEventListener("pointerenter",()=>ring.classList.add("active"));el.addEventListener("pointerleave",()=>ring.classList.remove("active"))})}
if(!reduced)$$(".magnetic").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform=`translate(${x*.12}px,${y*.12}px)`});el.addEventListener("pointerleave",()=>el.style.transform="")});
if(!reduced&&matchMedia("(pointer:fine)").matches)$$(".tilt").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`rotateX(${-y*5}deg) rotateY(${x*7}deg)`});el.addEventListener("pointerleave",()=>el.style.transform="")});
const canvas=$("#ambient"),ctx=canvas.getContext("2d");let particles=[],w=0,h=0,dpr=1;function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(70,Math.floor(w/18))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.2+.2,v:Math.random()*.12+.03,a:Math.random()*.22+.04}))}addEventListener("resize",resize);resize();function ambient(){ctx.clearRect(0,0,w,h);for(const p of particles){p.y-=p.v;if(p.y<-5){p.y=h+5;p.x=Math.random()*w}ctx.beginPath();ctx.fillStyle=`rgba(217,255,67,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(ambient)}if(!reduced)ambient();
const dialog=$("#caseDialog"),caseContent=$("#caseContent");function openCase(key){const c=cases[key];if(!c)return;caseContent.innerHTML=`<section class="case-hero" style="--case-accent:${c.accent}"><span class="case-index">${c.index}</span><h2>${c.title}</h2><p>${c.intro}</p></section><section class="case-details"><div><small>Role</small><b>${c.role}</b></div><div><small>Year</small><b>${c.year}</b></div><div><small>Scope</small><b>${c.scope}</b></div></section>`;dialog.showModal()}$$(".project").forEach(card=>{const go=()=>openCase(card.dataset.project);card.addEventListener("click",go);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go()}})});$(".case-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
const palette=$("#palette"),paletteInput=$("#paletteInput");function openPalette(){if(!palette.open){palette.showModal();paletteInput.value="";setTimeout(()=>paletteInput.focus(),0)}}$("#openPalette").addEventListener("click",openPalette);addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette()}if(e.key==="Escape"&&palette.open)palette.close()});paletteInput.addEventListener("input",e=>{const q=e.target.value.toLowerCase();$$(".palette-list button").forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q))});$(".palette-list").addEventListener("click",e=>{const button=e.target.closest("button");if(!button)return;palette.close();document.querySelector(button.dataset.go)?.scrollIntoView({behavior:"smooth"})});palette.addEventListener("click",e=>{if(e.target===palette)palette.close()});
$$("[data-scroll]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));if(!reduced)addEventListener("scroll",()=>{const art=$(".hero-art");if(scrollY<innerHeight*1.2)art.style.transform=`translateY(${scrollY*.09}px)`},{passive:true});